apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: each-cluster-service-sync-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <argo_repo_url>
    path: cluster/qin-cluster
  destination:
    name: in-cluster # 自己本身
    namespace: argocd
  syncPolicy:
    syncOptions:
      - PreserveResourcesOnDeletion=true # 避免頂級資源被刪除
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true