apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-application
spec:
  project: qin-app-project
  source:
    repoURL: <argo_repo_url>
    targetRevision: HEAD
    path: 'cluster/qin-cluster/service/rabbitmq/manifest'
  destination:
    name: qin-cluster
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true