apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
    namespace: rabbitmq-system
spec:
  image: rabbitmq:3.13.7-management
  replicas: 3
  persistence:
    storageClassName: longhorn
    storage: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      default_user=admin
      default_pass=password