apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.service | lower | quote }}
  namespace: {{ .Values.namespace | lower | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.service | lower | quote }}
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.version }}
    metadataVersion: {{ .Values.metadataVersion }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: {{ .Values.bootstrapPort }}
          {{- if .Values.nodePorts }}
          {{ printf "brokers:" }}
          {{- range $index, $port := .Values.nodePorts }}
          {{ printf "- broker:"}} {{ $index }}
          {{ printf "  nodePort:"}} {{ $port }}
          {{- end }}
          {{- end }}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ printf "%s-exporter" (.Values.service | lower) | quote }}
          key: kafka-metrics-config.yml
  kafkaExporter:
    resources:
      requests:
        memory: 256Mi
        cpu: "100m"
      limits:
        memory: 512Mi
        cpu: "200m"