apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-exporter" (.Values.service | lower) | quote }}
  namespace: {{ .Values.namespace | lower | quote }}
  labels:
    prometheus.io/scrape: "true"
    strimzi.io/cluster: {{ .Values.service | lower | quote }}
    app.kubernetes.io/name: {{ printf "%s-exporter" (.Values.service | lower) | quote }}
spec:
  selector:
    app.kubernetes.io/name: kafka-exporter
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404