apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-redpanda" (.Values.service | lower) | quote }}
  namespace: {{ .Values.namespace | lower | quote }}
spec:
  type: NodePort
  selector:
    app: {{ printf "%s-redpanda" (.Values.service | lower) | quote }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.redpandaPort }}